baseURL = "https://losgobbi.github.io/"
title = "losgobbi"
languageCode = "en-us"
theme = "devise"
#relativeURLs = true
enableEmoji = true
googleAnalytics = ""
enableRobotsTXT = true
copyright = "personal blog :)"

[outputs]
home = ["HTML", "RSS"]

[outputFormats]
[outputFormats.RSS]
mediaType = "application/rss+xml"
baseName = "index"
isPlainText = true
notAlternative = true

# Main menu items
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/myself"
    weight = -110
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = -100

[taxonomies]
  category = "categories"

# Configuration Features
[params]
  baseURL = "https://losgobbi.github.io/"
  description = "AOSP / Kernel / Android"      # Your meta description of the site
  header_title = "Rodrigo Gobbi"                 # Your header title
  header_subtitle = "Some software experiments ;)" # Your header subtitle
  home_image = "losgobbi.jpeg"          # Path to header image starting from the static directory (optional)
  recent_posts = 3                           # Max amount of recent posts to show
  mainSections = ["posts", "blog"]   # Main sections to include in recent posts
  [params.style]                             # CSS style overrides
    backgroundColor = "#f8f9fa"
    homeImageBorderColor = "#ffffff"
    fontFamilyBase = "Helvetica Neue"        # First-choice font
    fontColor = "#212529"
  [[params.social]]
    fa_icon = "fab fa-github fa-1x"          # Font Awesome icon class
    href = "http://github.com/losgobbi"      # Link to associate with icon (http://, https://, mailto:)
  [[params.social]]
    fa_icon = "fab fa-linkedin-in fa-1x"
    href = "http://www.linkedin.com/in/rodrigo-gobbi"
 [[params.social]]
    fa_icon = "fas fa-rss fa-1x"
    href = "/posts/index.xml"

# use html inside mk
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "monokailight"
  [markup.tableOfContents]
    startLevel = 4
    endLevel = 6
    ordered = false